#!/sbin/busybox sh

# trigger button-backlight
busybox echo '255' > /sys/class/leds/red/brightness
busybox echo '255' > /sys/class/leds/green/brightness
busybox echo '255' > /sys/class/leds/blue/brightness
busybox echo '255' > /sys/class/leds/button-backlight/brightness

busybox sleep 3

# trigger button-backlight
busybox echo '0' > /sys/class/leds/red/brightness
busybox echo '0' > /sys/class/leds/green/brightness
busybox echo '0' > /sys/class/leds/blue/brightness
busybox echo '0' > /sys/class/leds/button-backlight/brightness
